import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme/provider";
import Nav from "@/components/nav";
import QueryProvider from "@/lib/react-query/provider"
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from 'sonner'

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "font-sans antialiased overflow-hidden",
          fontSans.variable,
          "w-screen h-screen"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          disableTransitionOnChange
        >
          <QueryProvider>
            <div className="w-screen h-screen overflow-hidden flex">
              <div className="w-14 h-full flex flex-col shrink-0 grow-0">
                <Nav />
              </div>
              {children}
              <Toaster />
            </div>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
